
web:
  build: .
  command: ./main
  ports:
    - "8080:8080"
  links:
    - redis:r
    - rabbitmq:rmq
    - mongodb:m
  environment:
#    - MONGODB_URI: ${MONGODB_1_PORT}

    PORT: "8080"




redis:
  image: redis

  ports:
    - "6379:6379"

rabbitmq:
  image: rabbitmq

  ports:
    - "5672:5672"

mongodb:
  image: mongo

  ports:
    - "27017:27017"




