
web:
  build: .
  command: ./main
  ports:
    - "8080:8080"
  links:
    - redis:r
    - rabbitmq:rmq
    - mongodb:m
    - neo4j:n

  environment:
#    - MONGODB_URI: ${MONGODB_1_PORT}

    PORT: "8080"
    NODE_DATA_SERVICE: "http://ss-node-data-staging.herokuapp.com"

redis:
  image: redis

  ports:
    - "6379:6379"
#
rabbitmq:
  image: rabbitmq

  ports:
    - "5672:5672"
    - "15672:15672"

mongodb:
  image: mongo

  ports:
    - "27017:27017"
neo4j:
  image: neo4j

  ports:
    - "7474:7474"
    - "7473:7473"
    - "7687:7687"
    - "1337:1337"




